# Generated by Django 2.1.5 on 2019-02-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Joao Mendes', max_length=256, verbose_name='Login'),
            preserve_default=False,
        ),
    ]
