# Generated by Django 2.1.5 on 2019-02-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190227_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='function',
            field=models.CharField(choices=[('CO', 'Colaborador'), ('SU', 'Supervisor')], default='CO', max_length=2),
        ),
    ]
