# Generated by Django 2.1.5 on 2019-03-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190324_1710'),
        ('users', '0002_auto_20190226_0313'),
    ]

    operations = [
    ]
