version: "3"
services:
    web:
        build:
            context: .
            dockerfile: docker-compose/Dockerfile_dev
        volumes: 
            - .:/app
        stdin_open: true
        tty: true
        ports:
            - "8000:8000"
        env_file:
            - .env


    # postgres:
