# Generated by Django 2.0 on 2019-07-01 19:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('call_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Número da Ligação')),
                ('call_24_hours', models.BooleanField(default=False, verbose_name='Chamada adiada')),
                ('email_sended', models.BooleanField(default=False, verbose_name='Email enviado')),
                ('paid', models.BooleanField(default=False, verbose_name='Pagamento efetuado')),
                ('notes', models.TextField(max_length=256, verbose_name='Anotações')),
                ('status', models.CharField(choices=[('RECEBIDA', 'Recebida'), ('ATENDIDA', 'Atendida'), ('NAO_ATENDIDA', 'Não Atendida'), ('ABANDONADA', 'Abandonada'), ('OCUPADO', 'Ocupado'), ('EM PROGRESSO', 'Em Progresso'), ('PENDENTE', 'Pendente')], default='RC', max_length=12, verbose_name='Status')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor')),
                ('date_scheduling', models.DateTimeField(verbose_name='Data e Hora da ligação')),
            ],
            options={
                'verbose_name': 'Chamada',
                'verbose_name_plural': 'Chamadas',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nome')),
                ('company_name', models.CharField(max_length=40, verbose_name='Empresa')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('cellphone', models.CharField(max_length=20, verbose_name='Celular')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('adress', models.CharField(max_length=256, verbose_name='Endereço')),
                ('last_update', models.DateTimeField(default=datetime.datetime.now, verbose_name='Última atualização')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo')], default='AC', max_length=8, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Assunto',
                'verbose_name_plural': 'Assuntos',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='tag',
            field=models.ManyToManyField(to='calls.Tag', verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='call',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.Contact', verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='call',
            name='subject',
            field=models.ManyToManyField(max_length=3, to='calls.Subject', verbose_name='Assunto'),
        ),
    ]
