# Generated by Django 2.1.5 on 2019-04-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('RECEBIDAS', 'Recebida'), ('ATENDIDA', 'Atendida'), ('NAO_ATENDIDA', 'Não Atendida'), ('ABANDONADA', 'Abandonada')], default='RC', max_length=12, verbose_name='Status'),
        ),
    ]
