# Generated by Django 2.1.5 on 2019-04-18 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('RECEBIDA', 'Recebida'), ('ATENDIDA', 'Atendida'), ('NAO_ATENDIDA', 'Não Atendida'), ('ABANDONADA', 'Abandonada')], default='RC', max_length=12, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cellphone',
            field=models.CharField(help_text='O número deve ser cadastrado da seguinte forma:                  (DD)9-9999-9999', max_length=20, validators=[django.core.validators.RegexValidator(message='O número deve ser cadastrado da seguinte forma:                (DD)9-9999-9999', regex='^\\(\\d{2}\\)\\d{1}-\\d{4}-\\d{4}$')], verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=256, validators=[django.core.validators.RegexValidator(message='O email deve ser cadastrado da seguinte forma:                 email@email.com', regex='^([\\w\\-]+\\.)*[\\w\\- ]+@([\\w\\- ]+\\.)+([\\w\\-]{2,3})$')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(help_text='O número deve ser cadastrado da seguinte forma:                (DD)9999-9999', max_length=20, validators=[django.core.validators.RegexValidator(message='O número deve ser cadastrado da seguinte forma:                (DD)9999-9999', regex='^\\(\\d{2}\\)\\d{4}-\\d{4}$')], verbose_name='Telefone'),
        ),
    ]
