# Generated by Django 2.1.7 on 2019-02-21 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'verbose_name': 'Chamada', 'verbose_name_plural': 'Chamadas'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Assunto', 'verbose_name_plural': 'Assuntos'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='call',
            name='call_24_hours',
            field=models.BooleanField(default=False, verbose_name='Chamada adiada'),
        ),
        migrations.AlterField(
            model_name='call',
            name='email_sended',
            field=models.BooleanField(default=False, verbose_name='Email enviado'),
        ),
        migrations.AlterField(
            model_name='call',
            name='notes',
            field=models.TextField(max_length=256, verbose_name='Anotações'),
        ),
        migrations.AlterField(
            model_name='call',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Pagamento efetuado'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cellphone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='O número deve ser cadastrado da seguinte forma: (DD) 9 9999-9999', regex='^\\(\\d{2}\\)\\d{1}\\s\\d{4}-\\d{4}$')], verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=256, validators=[django.core.validators.RegexValidator(message='O email deve ser cadastrado da seguinte forma: email@email.com', regex='^([\\w\\-]+\\.)*[\\w\\- ]+@([\\w\\- ]+\\.)+([\\w\\-]{2,3})$')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='O número deve ser cadastrado da seguinte forma: (DD) 9999-9999', regex='^\\(\\d{2}\\)\\d{4}-\\d{4}$')], verbose_name='Telefone'),
        ),
    ]
