# Generated by Django 2.1.5 on 2019-04-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='hour',
            field=models.TimeField(auto_now=True, verbose_name='Hora da Ligação'),
        ),
    ]
