# Generated by Django 2.1.5 on 2019-04-16 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_auto_20190416_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='hour',
            field=models.TimeField(default=datetime.time, verbose_name='Hora da Ligação'),
        ),
    ]
