# Generated by Django 2.1.5 on 2019-04-16 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_auto_20190416_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Última atualização'),
        ),
    ]
