# Generated by Django 2.1.7 on 2019-02-22 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_auto_20190221_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cellphone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='O número deve ser cadastrado da seguinte forma: (DD)9-9999-9999', regex='^\\(\\d{2}\\)\\d{1}-\\d{4}-\\d{4}$')], verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='O número deve ser cadastrado da seguinte forma: (DD)9999-9999', regex='^\\(\\d{2}\\)\\d{4}-\\d{4}$')], verbose_name='Telefone'),
        ),
    ]
