# Generated by Django 2.1.5 on 2019-04-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_call_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('BUSY', 'Ativo'), ('IN_PROGRESS', 'Em Progresso'), ('PENDING', 'Pendente')], default='IN', max_length=256, verbose_name='Status'),
        ),
    ]
