# Generated by Django 2.1.5 on 2019-05-06 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_auto_20190418_2027'),
        ('calls', '0003_auto_20190416_0920'),
    ]

    operations = [
    ]
