# Generated by Django 2.1.7 on 2019-02-22 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_auto_20190222_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='contact',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='calls.Contact'),
        ),
    ]
