# Generated by Django 2.1.5 on 2019-04-15 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_call_status'),
        ('calls', '0003_auto_20190403_2116'),
    ]

    operations = [
    ]
