# Generated by Django 2.1.5 on 2019-04-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_auto_20190416_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor'),
        ),
    ]
