# Generated by Django 2.1.7 on 2019-02-22 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_call_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.Contact'),
        ),
    ]
