# Generated by Django 2.1.5 on 2019-04-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_call_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('RECEBIDA', 'Recebida'), ('ATENDIDA', 'Atendida'), ('NAO_ATENDIDA', 'Não Atendida'), ('ABANDONADA', 'Abandonada'), ('OCUPADO', 'Ocupado'), ('EM PROGRESSO', 'Em Progresso'), ('PENDENTE', 'Pendente')], default='RC', max_length=12, verbose_name='Status'),
        ),
    ]
