# Generated by Django 2.1.7 on 2019-02-22 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_auto_20190222_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.Contact', verbose_name='Contato'),
        ),
    ]
