# Generated by Django 2.1.5 on 2019-05-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_merge_20190506_1135'),
        ('calls', '0006_merge_20190506_1154'),
    ]

    operations = [
    ]
