# Generated by Django 2.1.5 on 2019-02-22 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_auto_20190222_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='subject',
        ),
        migrations.AddField(
            model_name='call',
            name='subject',
            field=models.ManyToManyField(to='calls.Subject', verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cellphone',
            field=models.CharField(help_text='O número deve ser cadastrado da seguinte forma: (DD)9-9999-9999', max_length=20, validators=[django.core.validators.RegexValidator(message='O número deve ser cadastrado da seguinte forma: (DD)9-9999-9999', regex='^\\(\\d{2}\\)\\d{1}-\\d{4}-\\d{4}$')], verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(help_text='O número deve ser cadastrado da seguinte forma: (DD)9999-9999', max_length=20, validators=[django.core.validators.RegexValidator(message='O número deve ser cadastrado da seguinte forma: (DD)9999-9999', regex='^\\(\\d{2}\\)\\d{4}-\\d{4}$')], verbose_name='Telefone'),
        ),
    ]
