# Generated by Django 2.1.5 on 2019-05-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_merge_20190509_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('RECEBIDA', 'Recebida'), ('ATENDIDA', 'Atendida'), ('NAO_ATENDIDA', 'Não Atendida'), ('ABANDONADA', 'Abandonada'), ('OCUPADO', 'Ocupado'), ('EM PROGRESSO', 'Em Progresso'), ('PENDENTE', 'Pendente')], default='RC', max_length=12, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cellphone',
            field=models.CharField(max_length=20, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=256, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
