# Generated by Django 2.1.5 on 2019-02-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_auto_20190222_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='tag',
        ),
        migrations.AddField(
            model_name='contact',
            name='tag',
            field=models.ManyToManyField(to='calls.Tag', verbose_name='Tag'),
        ),
    ]
