# Generated by Django 2.1.5 on 2019-03-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0008_auto_20190222_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='subject',
            field=models.ManyToManyField(max_length=3, to='calls.Subject', verbose_name='Assunto'),
        ),
    ]
