# Generated by Django 2.1.5 on 2019-05-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0008_auto_20190509_1202'),
        ('calls', '0007_merge_20190517_0909'),
    ]

    operations = [
    ]
