# Generated by Django 2.1.5 on 2019-05-24 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0008_auto_20190509_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='date_scheduling',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Data e Hora da ligação'),
        ),
    ]
