# Generated by Django 2.1.5 on 2019-05-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0009_call_date_scheduling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='date_scheduling',
            field=models.DateTimeField(verbose_name='Data e Hora da ligação'),
        ),
    ]
