# Generated by Django 2.1.5 on 2019-03-13 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0009_auto_20190223_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cellphone',
            field=models.CharField(help_text='O número deve ser cadastrado da seguinte forma:                    (DD)9-9999-9999', max_length=20, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=256, validators=[django.core.validators.RegexValidator(message='O email deve ser cadastrado da seguinte forma:                    email@email.com', regex='^([\\w\\-]+\\.)*[\\w\\- ]+@([\\w\\- ]+\\.)+([\\w\\-]{2,3})$')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Última atualização'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(help_text='O número deve ser cadastrado da seguinte forma:                    (DD)9999-9999', max_length=20, verbose_name='Telefone'),
        ),
    ]
