# Generated by Django 2.1.5 on 2019-05-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0010_auto_20190524_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='duration',
        ),
    ]
